### ISSUE TITLE
Strange Spacing

### ISSUE THREAD

**Issue by Bo-Ru** [jaywilkas/xpytile#1]
I have a xfce4-bar on the left. It's odd that it reserves space, but not on the left. It's on the right instead. This makes windows go under the bar and having space at the right where nothing is there.

**Comment by jaywilkas** [comment]
Thats right, the script is not taking the position of the xfce4-bar into account.
It just checks the size of the remaining screen space.
I will (try to) fix that.

**Comment by jaywilkas** [comment]
Hi supertux,

first of all, thanks for taking a look at xpytile.
You are right, the script is not taking the position of the xfce4-bar into account.

It just checks the size of the remaining screen space.
I will (try to) fix that.

 

Greetings

**Comment by jaywilkas** [comment]
fixed
