### ISSUE TITLE
Add support for client-side-decoration in XFCE 4.18

### ISSUE THREAD

**Issue by j-zero** [jaywilkas/xpytile#10]
Hi,

I'm running Arch with XFCE 4.18 on my old laptop and i really like xpytile! Thank you!
But, there is a problem with client side decorated windows (CSD) like GTK 3/4 (e.g. Firefox): 
![Bildschirmfoto_2023-05-09_23-09-08](https://github.com/jaywilkas/xpytile/assets/504831/9623b932-8f4b-4fa8-a4b5-c0448197a943)

As you can see, the window decoration is server side in tiling mode.

Any ideas how to fix this?

**Comment by jaywilkas** [comment]
I must admit, currently I don't have a clue.
Let me try to figure this out.
As a work around you could turn off CSD for Firefox.

**Comment by j-zero** [comment]
I think this happens because of two things:
1. You force the server-side decoration with `window.change_property(MOTIF_WM_HINTS, MOTIF_WM_HINTS, 32, hints)`in the set_decoration method, even if the window originally didn't have server-side decoration.
2. The window has an invisible border (gtk3/4?) which causes the "inner" window not to fit in the tile.

I'm completely new to Python, GTK3, xlib and stuff. So that are wild guesses :shrug:

**Comment by j-zero** [comment]
I think the first part would be "easy" to fix. My suggestion would be: Don't force the window decoration.
On toggling the borders, just look, if the windows has the MOTIF_WM_HINTS for decoration, if not, don't touch it. If it has: save the window id in an array. If the user toggles back, just reset the hints to the original state.
Same on window creation. Just make a backup and put it back on toggle.

The second part could be a GTK problem, not xlib.

**Comment by jaywilkas** [comment]
The script now checks whether a windows uses client-side-decoration and if so doesn't toggle the borders.

**Comment by j-zero** [comment]
Damn, it works like charm. Thank you!

**Comment by jaywilkas** [comment]
Hi j-zero,

can you tell me which (preferably) small Qt application with CSD causes the same problem?

**Comment by j-zero** [comment]
For me it's the original Telegram client.

**Comment by jaywilkas** [comment]
In the config-file you can now define which (Qt-)applications have client-side decoration and should not be (un)decorated by xpytile.
