### ISSUE TITLE
How to disable auto resize of the terminal windows?

### ISSUE THREAD

**Issue by rusttest5578** [jaywilkas/xpytile#11]
I would like to create this specific setup:
- whenever I launch a new terminal, the terminal should be launched in the upper-left size of my screen, and should not be resized.
- stack a maximum of 3 windows horizontally, and then move to the next column.

I have tried to modify the config file to achieve this but nothing seems to suit my needs. Is there a way I could configure this behaviour?

**Comment by jaywilkas** [comment]
Hi rusttest5578,

there is no function in xpytile to place a certain application (in your case the terminal) after launching it at a fixed position.
You can configure xpytile to not resize certain apps. But then this app also wont be taken into account regarding the tiling, and I think this is not what you want. When I get you correctly, you want that the terminal program to always sit in the upper-left size of the screen and up to 3 windows should be tiled as usual in xpytile, except the terminal program should always stay in place.

Unfortunately this behaviour can't be achieved - at least not without adding such a function to the script.

As a possible solution you could send the launched terminal window to the left side of your screen ('mod - ESC' per default) by making it the master window, provided the master-and-stack - layout is active.
In case this is a viable solution, you could automate this with a small script. That script, triggered by a hotkey, would then launch the terminal-programm and then remotely controls xpytile to send the windows to the left side - see "swap active window with the top most- / left- one" in xpytilerc, command #9 and the xpytile-remote-control.py - script)

**Comment by rusttest5578** [comment]
Thanks for the response. I will try something else then.
