### ISSUE TITLE
Some Windows With Originally No Borders Have Borders After Running The Script

### ISSUE THREAD

**Issue by Bo-Ru** [jaywilkas/xpytile#2]
Thanks for the fix last time, it's working properly now. But however since I use Ulauncher, which originally has no borders, become the opposite after running the script. It may be a feature instead of a bug, but is it possible to disable it in the configuration file?

**Comment by jaywilkas** [comment]
You can add ulauncher to the list of ignored applications in the config-file.
Ulauncher will then be totally ignored, i.e. no tiling, no auto-resizing
and no adding or removing of borders.

Does this solve your problem ?

For possible further questions, please send me an email to <just4 [period] gmail [at] web [period] de>

**Comment by jaywilkas** [comment]
Not an issue. 
Edit the config file to achive the wanted behaviour.
