### ISSUE TITLE
Ascii char for ctrl+alt or shift+alt

### ISSUE THREAD

**Issue by Heclalava** [jaywilkas/xpytile#4]
I am trying to run ctrl+alt or shift+alt as my hotkey modifier. getModifierCode.py doesn't register these key combos, also when I run getModifierCode.py I gett the following error: 
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 477, sequence_number = 14, major_opcode = 33, minor_opcode = 0

I have searched for the ascii codes for this key combination but not having any luck. Do you know what the decimal number is for key combinations? Also code 64 doesn't work for my SuperL according to ascii in terminal code 64=@. 

I have the hotkey modifier set to 18, which is Caps Lock. It works, but I have to constantly check that caps lock is off when I type.

**Comment by jaywilkas** [comment]
Hi Heclalava,

the modifier code for Ctrl-Alt is 28
and for Shift-Alt is 25.
If 64 for SuperL doesn't work for you, try 80.

**Comment by Heclalava** [comment]
Thanks, I have it working with Ctrl+Alt now.
