### ISSUE TITLE
Suggestion: ignore Ulauncher

### ISSUE THREAD

**Issue by st-a** [jaywilkas/xpytile#9]
Hi, thanks for the great script!

Would you mind adding `name: "Ulauncher"` to the default `ignoreWindows`? Ulauncher is an application launcher, which appears as a temporary overlayed input box: https://ulauncher.io/.

I think this would benefit a lot of keyboard oriented XFCE users.

**Comment by jaywilkas** [comment]
Thanks for the suggestion!
I added Ulauncher and rofi to the default ignoreWindows.

**Comment by jaywilkas** [comment]
suggestion implemented
